name: github pages

on:
  push:
    branches:
      - main # default branch

jobs:
  deploy:
    runs-on: ubuntu-latest # 使用 runner 最新版，防止 GitHub actions 运行不起来
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      # 文档编译命令，如果是 react 模板需要修改为 npm run docs:build
      - run: yarn build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # 文档目录，如果是 react 模板需要修改为 docs-dist
          publish_dir: ./dist
